In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

### Hitunglah:

1. 2*A
2. 2+A
3. A+B
4. A-B
5. determinan A
6. invers dari B, simpan jadi matriks D
7. transpose D
8. nilai eigen dan vektor eigen dari A dan B

In [3]:
print(2*A)

[[ 2  4]
 [14 16]]


In [4]:
print(2 + A)

[[ 3  4]
 [ 9 10]]


In [5]:
print(A+B)

[[ 4  7]
 [ 8 14]]


In [6]:
print(A-B)

[[-2 -3]
 [ 6  2]]


In [7]:
print('Determinan', np.linalg.det(A))

Determinan -6.0


In [8]:
D = np.linalg.inv(B)

In [9]:
print(D.transpose())

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [10]:
eig_val, eign_vec= np.linalg.eig(A)

In [11]:
print('Eigen Value A = \n',eig_val)

Eigen Value A = 
 [-0.62347538  9.62347538]


In [12]:
print('Eigen Vector A = \n',
      eign_vec)

Eigen Vector A = 
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [13]:
eig_val, eign_vec= np.linalg.eig(B)

In [14]:
print('Eigen Value B = \n',eig_val)

Eigen Value B = 
 [1.8074176 7.1925824]


In [15]:
print('Eigen Vector B = \n',
      eign_vec)

Eigen Vector B = 
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


#### Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?


In [16]:
print("perkalian antar entry di B dan D = \n",B*D)

perkalian antar entry di B dan D = 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [17]:
print("perkalian matriks B dan D = \n",np.matmul(B,D))

perkalian matriks B dan D = 
 [[ 1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]]


perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308, 1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16], [ 1.11022302e-16, 1.00000000e+00]]